intermediate

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2350,9 +2350,50 @@ echo "${ECHO_T}no" >&6
 fi
 
   if test -z "$PYTHON_BIN"; then
-    { { echo "$as_me:$LINENO: error: python binary not found in path" >&5
+    # Extract the first word of "python2.4", so it can be a program name with args.
+set dummy python2.4; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_PYTHON_BIN+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $PYTHON_BIN in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_PYTHON_BIN="$PYTHON_BIN" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_PYTHON_BIN="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  ;;
+esac
+fi
+PYTHON_BIN=$ac_cv_path_PYTHON_BIN
+
+if test -n "$PYTHON_BIN"; then
+  echo "$as_me:$LINENO: result: $PYTHON_BIN" >&5
+echo "${ECHO_T}$PYTHON_BIN" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+    if test -z "$PYTHON_BIN"; then
+       { { echo "$as_me:$LINENO: error: python binary not found in path" >&5
 echo "$as_me: error: python binary not found in path" >&2;}
    { (exit 1); exit 1; }; }
+    fi
   fi
 fi
 
@@ -2369,9 +2410,11 @@ echo "${ECHO_T}$PyVERSION, fantastic." >&6
 # make sure Python is version 2
 
 if test "$PyVERSION" != "2.3"; then
-  { { echo "$as_me:$LINENO: error: This version of only works with Python version 2.3. The one you have seems to be $PyVERSION." >&5
-echo "$as_me: error: This version of only works with Python version 2.3. The one you have seems to be $PyVERSION." >&2;}
+   if test "$PyVERSION" != "2.4"; then
+     { { echo "$as_me:$LINENO: error: This version of only works with Python version 2.3 and higher. The one you have seems to be $PyVERSION." >&5
+echo "$as_me: error: This version of only works with Python version 2.3 and higher. The one you have seems to be $PyVERSION." >&2;}
    { (exit 1); exit 1; }; }
+   fi
 fi
 
 # check for apxs
@@ -2558,7 +2601,7 @@ fi
 
 # final output
 
-                                                                                                              ac_config_files="$ac_config_files Makefile mkspec rhinit/Makefile scripts/Makefile openvps-admin.conf rhinit/openvps-recv www/conf/openvps-admin.conf www/Makefile www/conf/Makefile www/images/Makefile www/templates/Makefile"
+                                                                                                                                  ac_config_files="$ac_config_files Makefile mkspec rhinit/Makefile scripts/Makefile openvps-admin.conf rhinit/openvps-recv www/conf/openvps-admin.conf www/Makefile www/conf/Makefile www/images/Makefile www/templates/Makefile lib/python/openvps/admin/dft.py crontab/Makefile"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -3121,6 +3164,8 @@ do
   "www/conf/Makefile" ) CONFIG_FILES="$CONFIG_FILES www/conf/Makefile" ;;
   "www/images/Makefile" ) CONFIG_FILES="$CONFIG_FILES www/images/Makefile" ;;
   "www/templates/Makefile" ) CONFIG_FILES="$CONFIG_FILES www/templates/Makefile" ;;
+  "lib/python/openvps/admin/dft.py" ) CONFIG_FILES="$CONFIG_FILES lib/python/openvps/admin/dft.py" ;;
+  "crontab/Makefile" ) CONFIG_FILES="$CONFIG_FILES crontab/Makefile" ;;
   *) { { echo "$as_me:$LINENO: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
